FROM nginx:latest

# Copy custom Nginx config for Odoo
COPY /config/odoo-nginx.conf /etc/nginx/conf.d/

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Expose standard HTTP and HTTPS ports
EXPOSE 80 443